substitutions:
    _GCP_APP_NAME: "${GCP_APP_NAME}"
    _GCP_PROJECT_ID: "${GCP_PROJECT_ID}"
    _GCP_REGION: "${GCP_REGION}"
    _REPOSITORY: "${REPOSITORY}"
    _DBT_PROJECT_DIR: "src"
    _DBT_SERVICE_ACCOUNT: "${DBT_SERVICE_ACCOUNT_PROD}"

options:
    dynamic_substitutions: true
    substitution_option: 'ALLOW_LOOSE'
    logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'docker'
    args: ['build', 
            '--build-arg', 'BQ_PROJECT_ID=${_GCP_PROJECT_ID}', 
            '--build-arg', 'DBT_PROJECT_ID=${_DBT_PROJECT_ID}',
            '--build-arg', 'GOOGLE_APPLICATION_CREDENTIALS=${_DBT_SERVICE_ACCOUNT}',
            '--tag=$_GCP_REGION-docker.pkg.dev/$_GCP_PROJECT_ID/$_REPOSITORY/$_GCP_APP_NAME:latest',
            '--file=2-dbt/Dockerfile',
            '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_GCP_REGION-docker.pkg.dev/$_GCP_PROJECT_ID/$_REPOSITORY/$_GCP_APP_NAME:latest']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'jobs', 'deploy',
      '$_GCP_APP_NAME', '--image', '$_GCP_REGION-docker.pkg.dev/$_GCP_PROJECT_ID/$_REPOSITORY/$_GCP_APP_NAME:latest',
      '--set-env-vars', 'BQ_PROJECT_ID=${_GCP_PROJECT_ID}',
      '--set-env-vars', 'DBT_PROJECT_ID=${_DBT_PROJECT_ID}',
      '--set-env-vars', 'GOOGLE_APPLICATION_CREDENTIALS=${_DBT_SERVICE_ACCOUNT}',
      '--region', '$_GCP_REGION']
