name: "bigquery_public_data"
version: "1.0.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "bigquery_public_data"

model-paths: ["models"]
macro-paths: ["macros"]

vars:
  storage_uri: "gs://terraform-ambient-stone-394013/data/"

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"