bigquery_public_data:  # your profile name from dbt_project.yml
  target: prod  # your development environment
  outputs:
    
    dev:
      type: bigquery
      method: oauth
      project: ambient-stone-394013  # name of the project in BigQuery
      dataset: sandbox  # your dataset for development (usually your name)
      threads: 4
      timeout_seconds: 300
      priority: interactive
      retries: 1
    
    prod: # your production environment
      type: bigquery
      method: oauth 
      project: ambient-stone-394013  # name of the project in BigQuery
      dataset: ds_edw  # your dataset for production
      threads: 4
      timeout_seconds: 300
      priority: interactive
      retries: 1
