name: Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GCP_APP_NAME: ${{ secrets.GCP_APP_NAME }}
  GCP_PROJECT_ID:  ${{ secrets.GCP_PROJECT_ID }}
  GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_DBT_CREDENTIALS }}
  GCP_REGION: ${{ secrets.GCP_REGION }}
  REPOSITORY: ${{ secrets.REPOSITORY }}
  DBT_SERVICE_ACCOUNT_PROD: ${{ secrets.DBT_SERVICE_ACCOUNT_PROD }}

jobs:
    deploy:
        name: Setup dbt Plateform
        runs-on: ubuntu-latest
        env:
          IMAGE_NAME: ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.REPOSITORY }}/${{ secrets.GCP_APP_NAME }}:latest
        steps:

        - name: Login
          uses: google-github-actions/setup-gcloud@v1
          with:
            project_id: ${{ secrets.GCP_PROJECT_ID }}
            service_account_email: ${{ secrets.GCP_DBT_EMAIL }}
            service_account_key: ${{ secrets.GCP_DBT_CREDENTIALS }}

        - name: Checkout repository
          uses: actions/checkout@v3

        # Configure Workload Identity Federation and generate an access token.
        - id: 'auth'
          name: 'Authenticate to Google Cloud'
          uses: 'google-github-actions/auth@v1'
          with:
            credentials_json: '${{ secrets.GCP_DBT_CREDENTIALS }}'
            registry: '${{ secrets.GCP_REGION }}-docker.pkg.dev'
        - run: |-
            gcloud components install gke-gcloud-auth-plugin
            gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev --quiet
        # This example runs "docker login" directly to Artifact Registry.

        - name: Build, Push and Deploy dbt apps
          run: |-
            gcloud builds submit --config=cloudbuild.yaml --substitutions=_GCP_APP_NAME="${GCP_APP_NAME}",_GCP_PROJECT_ID="${GCP_PROJECT_ID}",_GCP_REGION="${GCP_REGION}",_REPOSITORY="${REPOSITORY}",_DBT_SERVICE_ACCOUNT="${DBT_SERVICE_ACCOUNT_PROD}" --region=europe-west1